name: Run K6 Tests in Cloud

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  k6-cloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Run K6 Cloud Tests
        uses: grafana/run-k6-action@v1
        with:
          path: test1.js
        env:
          K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
          K6_PROJECT_ID: ${{ secrets.K6_PROJECT_ID }}
